from pathlib import Path
import re

# =========================
# 基本設定
# =========================

BASE_DIR = Path(__file__).resolve().parent.parent

INPUT_FOLDER = BASE_DIR / "sample" / "api_outputs"
OUTPUT_FILE = BASE_DIR / "sample" / "final_output.md"


# =========================
# 從檔名取得排序資訊
# =========================

def get_file_number(file_path: Path) -> int:
    """
    Extract file number from filename.

    Example:
    001_1-8_翻譯.txt -> 1
    """

    match = re.match(r"(\d+)_", file_path.name)

    if not match:
        return 999999

    return int(match.group(1))


def get_title_from_filename(file_path: Path) -> str:
    """
    Convert filename into readable section title.

    Example:
    001_1-8_翻譯.txt -> FILE 001 | 1-8
    """

    match = re.match(r"(\d+)_(\d+-\d+)_翻譯", file_path.name)

    if not match:
        return file_path.stem

    file_no = match.group(1)
    number_range = match.group(2)

    return f"FILE {file_no} | {number_range}"


# =========================
# 合併 API 輸出
# =========================

def merge_outputs() -> int:
    if not INPUT_FOLDER.exists():
        raise FileNotFoundError(f"Input folder not found: {INPUT_FOLDER}")

    files = sorted(
        INPUT_FOLDER.glob("*_翻譯.txt"),
        key=get_file_number,
    )

    if not files:
        raise FileNotFoundError(f"No API output files found in: {INPUT_FOLDER}")

    output_lines = []

    output_lines.append("# Japanese Reading Assistant - Final Output")
    output_lines.append("")
    output_lines.append("This file is generated by merging all API output chunks.")
    output_lines.append("")

    for file in files:
        title = get_title_from_filename(file)
        text = file.read_text(encoding="utf-8").strip()

        output_lines.append("")
        output_lines.append("")
        output_lines.append(f"===== {title} =====")
        output_lines.append("")
        output_lines.append(text)

    OUTPUT_FILE.write_text("\n".join(output_lines).strip() + "\n", encoding="utf-8")

    return len(files)


# =========================
# 主程式
# =========================

def main() -> None:
    file_count = merge_outputs()

    print("API 輸出合併完成！")
    print(f"合併檔案數：{file_count}")
    print(f"輸出檔案：{OUTPUT_FILE}")


if __name__ == "__main__":
    main()